import {
    quicktype,
    InputData,
    jsonInputForTargetLanguage,
    JSONSchemaInput,
    FetchingJSONSchemaStore,
} from "quicktype-core";
import { write, file } from "bun";
import type {LanguageName} from "quicktype-core/dist/language/types";

async function quicktypeJSONSchema(targetLanguage: LanguageName, typeName: string, jsonSchemaString: string) {
    const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());
    await schemaInput.addSource({ name: typeName, schema: jsonSchemaString });
    const inputData = new InputData();
    inputData.addInput(schemaInput);

    return await quicktype({
        inputData,
        lang: targetLanguage,
        rendererOptions: {
            "just-types": "true"
        }
    });
}

async function quicktypeJSON(targetLanguage: LanguageName, typeName: string, jsonString: string) {
    const jsonInput = jsonInputForTargetLanguage(targetLanguage);
    await jsonInput.addSource({
        name: typeName,
        samples: [jsonString],
    });

    const inputData = new InputData();
    inputData.addInput(jsonInput);

    return await quicktype({
        inputData,
        lang: targetLanguage,
        rendererOptions: { "just-types": "true" }
    });
}

async function main() {
    console.log("Fetching Profile schema...");
    const response = await fetch("https://tim-schoenle.de/api/v1/profile/schema");
    if (!response.ok) {
        throw new Error("Failed to fetch schema");
    }
    const schemaString = await response.text();

    console.log("Reading WakaTime sample...");
    const wakaTimeSample = await file("scripts/sample-wakatime.json").text();

    console.log("Generating types...");
    const profileTypes = await quicktypeJSONSchema("typescript", "Profile", schemaString);
    const wakaResponseTypes = await quicktypeJSON("typescript", "WakaTime", wakaTimeSample);

    const content = "// Auto-generated by scripts/generate-types.ts\n" +
        profileTypes.lines.join("\n") + "\n\n" +
        wakaResponseTypes.lines.join("\n");

    await write("scripts/types.d.ts", content);
    console.log("Wrote scripts/types.d.ts");
}

if (import.meta.main) {
    await main();
}
