/**
 * Regenerates `scripts/types.ts` from the profile schema and one recorded WakaTime response.
 *
 * @remarks
 * The two halves of `types.ts` come from different places because the two APIs do. tim-schoenle.de
 * publishes a JSON Schema, so `Profile` is exact and is refetched on every run. WakaTime publishes
 * none, so `WakaTime` is inferred from `scripts/sample-wakatime.json`. That sample is committed
 * rather than fetched, which keeps the inferred half changing in a reviewed commit instead of
 * tracking whatever the API returned on the morning someone ran the generator.
 *
 * Nothing runs this in CI and nothing compares its output against the committed file, so
 * `types.ts` can be stale. Run `bun run gen-types` after the profile schema changes.
 *
 * @packageDocumentation
 */

import {
    quicktype,
    InputData,
    jsonInputForTargetLanguage,
    JSONSchemaInput,
    FetchingJSONSchemaStore,
} from "quicktype-core";
import { write, file } from "bun";
import type {LanguageName} from "quicktype-core/dist/language/types";

/** Renders `jsonSchemaString` as `targetLanguage` declarations, naming the root type `typeName`. */
async function quicktypeJSONSchema(targetLanguage: LanguageName, typeName: string, jsonSchemaString: string) {
    const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());
    await schemaInput.addSource({ name: typeName, schema: jsonSchemaString });
    const inputData = new InputData();
    inputData.addInput(schemaInput);

    return await quicktype({
        inputData,
        lang: targetLanguage,
        // Without this, quicktype also emits its runtime converters. generate-readme.ts casts the
        // response bodies rather than converting them, so the converters would be dead code in a
        // file nobody edits.
        rendererOptions: {
            "just-types": "true"
        }
    });
}

/**
 * Infers `targetLanguage` declarations from `jsonString` alone, naming the root type `typeName`.
 *
 * @remarks
 * Inference sees one document, so every property in it comes out required and a property the API
 * can omit does not appear at all. An empty array becomes `any[]`, and an ISO timestamp becomes
 * `Date`, which `JSON.parse` never returns.
 */
async function quicktypeJSON(targetLanguage: LanguageName, typeName: string, jsonString: string) {
    const jsonInput = jsonInputForTargetLanguage(targetLanguage);
    await jsonInput.addSource({
        name: typeName,
        samples: [jsonString],
    });

    const inputData = new InputData();
    inputData.addInput(jsonInput);

    return await quicktype({
        inputData,
        lang: targetLanguage,
        rendererOptions: { "just-types": "true" }
    });
}

/**
 * Overwrites `scripts/types.ts`, discarding anything edited there by hand.
 *
 * @throws If the schema cannot be fetched, or `scripts/sample-wakatime.json` is missing.
 */
async function main() {
    console.log("Fetching Profile schema...");
    const response = await fetch("https://tim-schoenle.de/api/v1/profile/schema");
    if (!response.ok) {
        throw new Error("Failed to fetch schema");
    }
    const schemaString = await response.text();

    console.log("Reading WakaTime sample...");
    const wakaTimeSample = await file("scripts/sample-wakatime.json").text();

    console.log("Generating types...");
    const profileTypes = await quicktypeJSONSchema("typescript", "Profile", schemaString);
    const wakaResponseTypes = await quicktypeJSON("typescript", "WakaTime", wakaTimeSample);

    const content = "// Auto-generated by scripts/generate-types.ts\n" +
        profileTypes.lines.join("\n") + "\n\n" +
        wakaResponseTypes.lines.join("\n");

    await write("scripts/types.ts", content);
    console.log("Wrote scripts/types.ts");
}

if (import.meta.main) {
    await main();
}
